logging:
  level.org.apache.http: DEBUG
  level.org.apache.http.headers: DEBUG
  level.org.springframework: DEBUG
  level.org.springframework.web: DEBUG
  level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---

spring:
  profiles: YaasJaxRsClientProfile

CustomerAccountGateway:
  tenant: tenanttwo
  scopes: hybris.customer_read, hybris.customer_update
  customerUrl: https://api.yaas.io/hybris/customer/v1/{tenant}/customers
  oauth2:
    tokenUrl: https://api.yaas.io/hybris/oauth2/v1/token
    client:
      id: RgBCu2uzXMXN8UKwg5CdEzgqmJuyIFl2
      secret: uR3HLnuPeA5KbPBK

---

spring:
    profiles: YaasAuthorizedTemplateProfile

CustomerAccountGateway:
  tenant: tenanttwo
  scopes: hybris.customer_read, hybris.customer_update
  customerUrl: https://api.yaas.io/hybris/customer/v1/{tenant}/customers
  oauth2:
    tokenUrl: https://api.yaas.io/hybris/oauth2/v1/token
    client:
      id: RgBCu2uzXMXN8UKwg5CdEzgqmJuyIFl2
      secret: uR3HLnuPeA5KbPBK

---

spring:
  profiles: SpringOAuth2Profile

CustomerAccountGateway:
  tenant: tenanttwo
  scopes: hybris.customer_read, hybris.customer_update
  customerUrl: https://api.yaas.io/hybris/customer/v1/{tenant}/customers
  oauth2:
    tokenUrl: https://api.yaas.io/hybris/oauth2/v1/token
    client:
      id: RgBCu2uzXMXN8UKwg5CdEzgqmJuyIFl2
      secret: uR3HLnuPeA5KbPBK
